/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_citt.vista;

import proyecto_citt.vista.totem_piso1.Auditorio;
import proyecto_citt.vista.totem_piso1.Cafeteria;
import proyecto_citt.vista.totem_piso1.Caja;
import proyecto_citt.vista.totem_piso1.Panol_mecanica;
import proyecto_citt.vista.totem_piso1.Primeros_auxilios;
import proyecto_citt.vista.totem_piso1.Taller_mecanica;
import proyecto_citt.vista.totem_piso1.sala105;
import proyecto_citt.vista.totem_piso1.sala106;
import proyecto_citt.vista.totem_piso1.sala107;
import proyecto_citt.vista.totem_piso1.sala108;


/**
 *
 * @author jaria
 */
public class Piso_1 extends javax.swing.JFrame {

    /**
     * Creates new form Piso_3
     */
    public Piso_1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_305 = new javax.swing.JButton();
        btn_308 = new javax.swing.JButton();
        btn_311 = new javax.swing.JButton();
        btn_sla_citt = new javax.swing.JButton();
        btn_312 = new javax.swing.JButton();
        btn_thw1 = new javax.swing.JButton();
        btn_tr1 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_inicio = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(768, 1360));
        setUndecorated(true);
        setSize(new java.awt.Dimension(768, 1360));

        jPanel1.setMaximumSize(new java.awt.Dimension(768, 1360));
        jPanel1.setMinimumSize(new java.awt.Dimension(768, 1360));
        jPanel1.setPreferredSize(new java.awt.Dimension(768, 1360));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 85)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRIMER PISO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 559, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELECCIONA TU SALA");
        jLabel2.setDoubleBuffered(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 500, 56));

        btn_305.setBackground(new java.awt.Color(51, 180, 154));
        btn_305.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_305.setForeground(new java.awt.Color(0, 50, 83));
        btn_305.setText("Taller Mecanica");
        btn_305.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_305ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_305, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 220, 101));

        btn_308.setBackground(new java.awt.Color(51, 180, 154));
        btn_308.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_308.setForeground(new java.awt.Color(0, 50, 83));
        btn_308.setText("Auditorio");
        btn_308.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_308ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_308, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 270, 240));

        btn_311.setBackground(new java.awt.Color(51, 180, 154));
        btn_311.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_311.setForeground(new java.awt.Color(0, 50, 83));
        btn_311.setText("Entrada");
        btn_311.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_311ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_311, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 840, 90, 101));

        btn_sla_citt.setBackground(new java.awt.Color(51, 180, 154));
        btn_sla_citt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_sla_citt.setForeground(new java.awt.Color(0, 50, 83));
        btn_sla_citt.setText("Caja");
        btn_sla_citt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sla_cittActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sla_citt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 840, 64, 101));

        btn_312.setBackground(new java.awt.Color(51, 180, 154));
        btn_312.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_312.setForeground(new java.awt.Color(0, 50, 83));
        btn_312.setText("Cafetería");
        btn_312.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_312ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_312, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 840, 130, 101));

        btn_thw1.setBackground(new java.awt.Color(51, 180, 154));
        btn_thw1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_thw1.setForeground(new java.awt.Color(0, 50, 83));
        btn_thw1.setText("Primeros Auxilios");
        btn_thw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thw1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_thw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 840, 160, 101));

        btn_tr1.setBackground(new java.awt.Color(51, 180, 154));
        btn_tr1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_tr1.setForeground(new java.awt.Color(0, 50, 83));
        btn_tr1.setText("108");
        btn_tr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tr1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 730, 120, 60));

        jButton17.setBackground(new java.awt.Color(51, 180, 154));
        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 50, 83));
        jButton17.setText("105");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 120, 70));

        jButton18.setBackground(new java.awt.Color(51, 180, 154));
        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 50, 83));
        jButton18.setText("106");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 120, 60));

        jButton19.setBackground(new java.awt.Color(51, 180, 154));
        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 50, 83));
        jButton19.setText("107");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 120, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_citt/vista/Imagenes/ASC.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 64, 101));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_citt/vista/Imagenes/BATH.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 690, 64, 101));

        btn_inicio.setBackground(new java.awt.Color(94, 90, 92));
        btn_inicio.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_inicio.setForeground(new java.awt.Color(255, 255, 255));
        btn_inicio.setText("Inicio");
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });
        jPanel1.add(btn_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 990, 140, 100));

        jButton20.setBackground(new java.awt.Color(51, 180, 154));
        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton20.setForeground(new java.awt.Color(0, 50, 83));
        jButton20.setText("Pañol Mecanica");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 140, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_citt/vista/Imagenes/Frame 2.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 660, 580));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 180, 154));
        jLabel7.setText("Busca tu sala");
        jLabel7.setDoubleBuffered(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, 72));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_citt/vista/Imagenes/HOME (1).png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(768, 1360));
        jLabel4.setMinimumSize(new java.awt.Dimension(768, 1360));
        jLabel4.setPreferredSize(new java.awt.Dimension(768, 1360));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sla_cittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sla_cittActionPerformed
        new Caja().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_sla_cittActionPerformed

    private void btn_305ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_305ActionPerformed
        new Taller_mecanica().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_305ActionPerformed

    private void btn_308ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_308ActionPerformed
        new Auditorio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_308ActionPerformed

    private void btn_311ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_311ActionPerformed
        
    }//GEN-LAST:event_btn_311ActionPerformed

    private void btn_312ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_312ActionPerformed
        new Cafeteria().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_312ActionPerformed

    private void btn_thw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thw1ActionPerformed
        new Primeros_auxilios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_thw1ActionPerformed

    private void btn_tr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tr1ActionPerformed
        new sala108().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_tr1ActionPerformed

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        new sala105().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        new Panol_mecanica().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        new sala106().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        new sala107().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piso_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piso_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piso_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piso_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Piso_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_305;
    private javax.swing.JButton btn_308;
    private javax.swing.JButton btn_311;
    private javax.swing.JButton btn_312;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_sla_citt;
    private javax.swing.JButton btn_thw1;
    private javax.swing.JButton btn_tr1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
